"""address line

Revision ID: 4eaf1f99c213
Revises: d0ef3a4cb94e
Create Date: 2025-05-28 04:12:44.595471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4eaf1f99c213"
down_revision: Union[str, None] = "d0ef3a4cb94e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_address", sa.Column("address_line", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_address", "address_line")
    # ### end Alembic commands ###
