"""new column in service category id

Revision ID: 5e6c7909a18a
Revises: 38abf6af6b62
Create Date: 2025-06-09 00:05:16.420252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6c7909a18a'
down_revision: Union[str, None] = '38abf6af6b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_categories', ['service_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'service_category_id')
    # ### end Alembic commands ###
