"""new columns is deleted

Revision ID: 72384f58e89d
Revises: 78034e6d23ce
Create Date: 2025-06-06 16:06:35.329730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72384f58e89d"
down_revision: Union[str, None] = "78034e6d23ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_providers", sa.Column("is_deleted", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "service_providers", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "is_deleted")
    op.drop_column("service_providers", "deleted_at")
    op.drop_column("service_providers", "is_deleted")
    # ### end Alembic commands ###
