"""address line

Revision ID: c2f08b37dca8
Revises: 4eaf1f99c213
Create Date: 2025-05-28 04:20:16.653081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f08b37dca8'
down_revision: Union[str, None] = '4eaf1f99c213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_address', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_address', 'pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('user_address', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_address', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_address', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_address', 'pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('user_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_address', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
