"""Add missing columns

Revision ID: dfa0588faad9
Revises: 87f63c8fdcec
Create Date: 2025-04-28 13:51:04.843910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa0588faad9'
down_revision: Union[str, None] = '87f63c8fdcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'locations', ['location_id'], ['id'])
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('providers', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('providers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('providers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'providers', 'services', ['service_id'], ['id'])
    op.add_column('service_provider_reviews', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'service_provider_reviews', 'services', ['service_id'], ['id'])
    op.add_column('services', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'category')
    op.drop_constraint(None, 'service_provider_reviews', type_='foreignkey')
    op.drop_column('service_provider_reviews', 'service_id')
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_column('providers', 'updated_at')
    op.drop_column('providers', 'created_at')
    op.drop_column('providers', 'service_id')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'location_id')
    # ### end Alembic commands ###
