"""provider-password

Revision ID: f8f8c2b22668
Revises: c2f08b37dca8
Create Date: 2025-06-02 23:58:49.394856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8f8c2b22668"
down_revision: Union[str, None] = "c2f08b37dca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_providers", sa.Column("password_hash", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_providers", "password_hash")
    # ### end Alembic commands ###
